### ISSUE TITLE
Subscribe Order Book Web Socket Error

### ISSUE THREAD

**Issue by dangell7** [XRPLF/xrpl-py#307]
Not sure if I am using the web socket correctly. I didn't see a test for this use case either, but maybe I missed it

Here is my code:

```
from xrpl.clients import WebsocketClient
from xrpl.models.requests import (
    Subscribe,
)
from xrpl.models.requests.subscribe import (
    SubscribeBook,
)
import xrpl.core.binarycodec.types.currency as currency


# Fetch
# [START] Fetch
def fetch(issuer, cur):
    """fetch."""
    url = "wss://s.altnet.rippletest.net/"
    sellBook = SubscribeBook(
        taker_gets=currency.Currency.from_value('XRP'),
        taker_pays=currency.Currency.from_value(cur),
        taker=issuer
    )
    print(sellBook)
    req = Subscribe(
        books=[sellBook]
    )
    with WebsocketClient(url) as client:
        client.send(req)
        for message in client:
            print(message)
# [END] Fetch
```

Here is my error:

`Object of type Currency is not JSON serializable`

The entire trace:

```
Traceback (most recent call last):
  File "/Users/denisangell/projects/xarket-maker/main.py", line 27, in <module>
    response = fetch_open_orders(issuer, currency)
  File "/Users/denisangell/projects/xarket-maker/open_orders.py", line 32, in fetch
    client.send(req)
  File "/Users/denisangell/.virtualenvs/xarket-market/lib/python3.9/site-packages/xrpl/clients/websocket_client.py", line 194, in send
    run_coroutine_threadsafe(self._do_send(request), self._loop).result()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/denisangell/.virtualenvs/xarket-market/lib/python3.9/site-packages/xrpl/asyncio/clients/websocket_base.py", line 162, in _do_send
    await self._do_send_no_future(request)
  File "/Users/denisangell/.virtualenvs/xarket-market/lib/python3.9/site-packages/xrpl/asyncio/clients/websocket_base.py", line 153, in _do_send_no_future
    json.dumps(
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Currency is not JSON serializable
```

**Comment by roukrak** [comment]
The first thing I see is you are using wrong classes to define the currencies.
Use the following:

For issued currencies:
from xrpl.models.currencies import IssuedCurrency

For XRP:
from xrpl.models.currencies import XRP

**Comment by ledhed2222** [comment]
Websockets in python are weird (at least for me). Here's how I would do what you're trying to do:


```python
from xrpl.clients import WebsocketClient
from xrpl.models import Subscribe, XRP, IssuedCurrency
from xrpl.models.requests.subscribe import SubscribeBook

URL = "wss://something"


def fetch(issuer):
  with WebsocketClient(URL) as client:
    client.send(Subscribe(
      books=[
        SubscribeBook(
          taker_gets=XRP(),
          taker_pays=IssuedCurrency(.....), # fill this in
          taker=issuer,
        ),
      ],
    ))
   for message in client:
      print(message)

**Comment by dangell7** [comment]
> The first thing I see is you are using wrong classes to define the currencies. Use the following:
> 
> For issued currencies: from xrpl.models.currencies import IssuedCurrency
> 
> For XRP: from xrpl.models.currencies import XRP

Yes this solves it. 

I had looked at the model [here](https://github.com/XRPLF/xrpl-py/blob/add-nft-support/xrpl/models/requests/subscribe.py)

Which is how I referenced the Currency. It must inherit but this works now.
