### ISSUE TITLE
OpenSSL missing RIPEMD160 on pythons3.7.9

### ISSUE THREAD

**Issue by mwanser1** [XRPLF/xrpl-py#339]
Maybe I'm missing something in the docs, but this package should work for python3.7.x but doesn't seem to work for 3.7.9.

With Python3.7.9 and 1.2.0 or 1.3.0 version of xrpl-py,  i get an assertion error on import saying "your OpenSSL implementation does not include the RIPEMD160 algorithm, which is required by XRPL".  If i use 3.10 it works so I'm assuming this isn't a configuration issue on my end.  

"from xrpl.clients import JsonRpcClient"
throws the following:
`Traceback (most recent call last):
  File ".\xrp_api.py", line 3, in <module>
    from xrpl.clients import JsonRpcClient
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\__init__.py", line 2, in <module>
    from xrpl import account, clients, core, ledger, models, transaction, utils, wallet
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\account\__init__.py", line 2, in <module>
    from xrpl.account.main import (
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\account\main.py", 
line 6, in <module>
    from xrpl.asyncio.account import main
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\asyncio\__init__.py", line 2, in <module>
    from xrpl.asyncio import account, clients, ledger, transaction, wallet 
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\asyncio\account\__init__.py", line 2, in <module>
    from xrpl.asyncio.account.main import (
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\asyncio\account\main.py", line 5, in <module>
    from xrpl.asyncio.clients import Client, XRPLRequestFailureException   
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\asyncio\clients\__init__.py", line 2, in <module>
    from xrpl.asyncio.clients.async_json_rpc_client import AsyncJsonRpcClient
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\asyncio\clients\async_json_rpc_client.py", line 2, in <module>
    from xrpl.asyncio.clients.async_client import AsyncClient
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\asyncio\clients\async_client.py", line 4, in <module>
    from xrpl.asyncio.clients.client import Client
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\asyncio\clients\client.py", line 6, in <module>
    from xrpl.models.requests.request import Request
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\models\__init__.py", line 2, in <module>
    from xrpl.models import amounts, currencies, requests, transactions    
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\models\requests\__init__.py", line 30, in <module>
    from xrpl.models.requests.sign import Sign
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\models\requests\sign.py", line 26, in <module>
    from xrpl.models.transactions.transaction import Transaction
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\models\transactions\__init__.py", line 6, in <module>
    from xrpl.models.transactions.account_delete import AccountDelete
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\models\transactions\account_delete.py", line 7, in <module>
    from xrpl.models.transactions.transaction import Transaction
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\models\transactions\transaction.py", line 9, in <module>
    from xrpl.core.binarycodec import encode
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\core\__init__.py", line 2, in <module>
    from xrpl.core import addresscodec, binarycodec, keypairs
  File "F:\code\xrp-data-db\venv2\lib\site-packages\xrpl\core\keypairs\__init__.py", line 19, in <module>
    which is required by XRPL"""
AssertionError: Your OpenSSL implementation does not include the RIPEMD160 algorithm,
    which is required by XRPL`

Windows 10 Pro, here are the packages that were installed from 'pip install xrpl-py':
anyio==3.4.0
base58==2.1.1
certifi==2021.10.8
ECPy==1.2.5
h11==0.12.0
httpcore==0.13.7
httpx==0.18.2
idna==3.3
pymongo==4.0.1
rfc3986==1.5.0
sniffio==1.2.0
typing-extensions==3.10.0.2
websockets==10.1
xrpl-py==1.3.0

**Comment by ledhed2222** [comment]
Hey there. Some versions of python 3.7 don't seem to play well with RIPEMD160. However, some do; for example, our tests use python 3.7.1 which does work.

The easiest solution here for you, if possible, is to use python 3.8+. If that's not possible, this really isn't an issue of xprl-py but rather a python issue itself. I can't find the python issue related to this, but i've seen it before. it's a known python 3.7 issue.

**Comment by ledhed2222** [comment]
this isn't the issue i was really looking for, but shows what i mean: https://bugs.python.org/issue38550

**Comment by mwanser1** [comment]
would have saved me several hours if there was a little asterisk in the docs saying 3.7 might be wonky.  maybe this info will help someone in the future.
