### ISSUE TITLE
Cannot create NFT

### ISSUE THREAD

**Issue by ObiajuluM** [XRPLF/xrpl-py#381]
```
from xrpl.models.transactions.nftoken_mint import NFTokenMint
from xrpl.wallet.wallet_generation import generate_faucet_wallet
from xrpl.transaction import (safe_sign_and_autofill_transaction,
                              send_reliable_submission)
import json

# connecting to a production server
# testnet_url = "https://xls20-sandbox.rippletest.net:51233"
testnet_url = "https://s.altnet.rippletest.net:51234/"
client = JsonRpcClient(testnet_url)

wallet_obj = generate_faucet_wallet(client)

my_payment = NFTokenMint(account=wallet_obj.classic_address,
nftoken_taxon=0)

print(my_payment)

signed_tx = safe_sign_and_autofill_transaction(
    my_payment,
    wallet_obj,
    client)

product = send_reliable_submission(signed_tx, client)

max_ledger = signed_tx.last_ledger_sequence
tx_id = signed_tx.get_hash()

print(product.status)
print(json.dumps(product.result, indent=2))

```

The code above used for creating NFT's returns an error.

```
NFTokenMint(account='rDBhGjrVDxvrfgpoLQYDFAXB5LsKH6mxYn', transaction_type=<TransactionType.NFTOKEN_MINT: 'NFTokenMint'>, fee=None, sequence=None, account_txn_id=None, flags=0, last_ledger_sequence=None, memos=None, signers=None, source_tag=None, signing_pub_key='', txn_signature=None, nftoken_taxon=0, issuer=None, transfer_fee=None, uri=None)
Traceback (most recent call last):
  File "C:\Users\0xEarl\Desktop\Learn_XRP\nft.py", line 36, in <module>
    product = send_reliable_submission(signed_tx, client)
  File "C:\Users\0xEarl\Desktop\Learn_XRP\venv\lib\site-packages\xrpl\transaction\reliable_submission.py", line 32, in send_reliable_submission
    return asyncio.run(async_send_reliable_submission(transaction, client))
  File "C:\Users\0xEarl\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\0xEarl\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\0xEarl\Desktop\Learn_XRP\venv\lib\site-packages\xrpl\asyncio\transaction\reliable_submission.py", line 90, in send_reliable_submission
    submit_response = await submit_transaction(transaction, client)
  File "C:\Users\0xEarl\Desktop\Learn_XRP\venv\lib\site-packages\xrpl\asyncio\transaction\main.py", line 142, in submit_transaction
    raise XRPLRequestFailureException(response.result)
xrpl.asyncio.clients.exceptions.XRPLRequestFailureException: Request failed, invalidTransaction: Unknown field
```

**Comment by ObiajuluM** [comment]
Ok, thanks
