### ISSUE TITLE
AttributeError: 'Wallet' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by YusufSina** [XRPLF/xrpl-py#424]
I was following the [Get Started Using Python](https://xrpl.org/get-started-using-python.html#get-started-using-python) but I got error on xrpl.transaction.autofill function.

```
from xrpl.clients import JsonRpcClient
client = JsonRpcClient("https://s.altnet.rippletest.net:51234/")
from xrpl.wallet import Wallet, generate_faucet_wallet
w1 = generate_faucet_wallet(client)
w2 = generate_faucet_wallet(client)
from xrpl.models.transactions import Payment
import xrpl.utils as XrpUtil
tx = Payment(account=w2, amount=XrpUtil.xrp_to_drops(1), destination=w1.classic_address)
import xrpl.transaction as Transaction
Transaction.autofill(tx, client)
```

then I got response

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yusuf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xrpl\transaction\main.py", line 138, in autofill
    return asyncio.run(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\yusuf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xrpl\asyncio\transaction\main.py", line 198, in autofill
    sequence = await get_next_valid_seq_number(transaction_json["account"], client)
  File "C:\Users\yusuf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xrpl\asyncio\account\main.py", line 60, in get_next_valid_seq_number
    int, (await get_account_root(address, client, ledger_index))["Sequence"]
  File "C:\Users\yusuf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xrpl\asyncio\account\main.py", line 101, in get_account_root
    account_info = await get_account_info(address, client, ledger_index)
  File "C:\Users\yusuf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xrpl\asyncio\account\main.py", line 126, in get_account_info
    if is_valid_xaddress(address):
  File "C:\Users\yusuf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xrpl\core\addresscodec\main.py", line 153, in is_valid_xaddress
    xaddress_to_classic_address(xaddress)
  File "C:\Users\yusuf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xrpl\core\addresscodec\main.py", line 87, in xaddress_to_classic_address
    decoded = base58.b58decode_check(
  File "C:\Users\yusuf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\base58\__init__.py", line 152, in b58decode_check
    result = b58decode(v, alphabet=alphabet, autofix=autofix)
  File "C:\Users\yusuf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\base58\__init__.py", line 117, in b58decode
    v = v.rstrip()
AttributeError: 'Wallet' object has no attribute 'rstrip'
```

**Comment by LimpidCrypto** [comment]
You passed in a Wallet object as source. Use `w2.classic_address` as you did with `w1`:

tx = Payment(account=w2.classic_address, amount=XrpUtil.xrp_to_drops(1), destination=w1.classic_address)

**Comment by YusufSina** [comment]
This is the answer of why pair programming is good :)

Thank you
