### ISSUE TITLE
Error network connetion

### ISSUE THREAD

**Issue by Hossein-Teimouri** [XRPLF/xrpl-py#621]
## program I wrote
```python
import xrpl
client = xrpl.clients.JsonRpcClient("http://127.0.0.1:5005")
address = input("address: ")
acc = xrpl.account.does_account_exist(address, client)
print(acc)
```
## output
```
address: rEgBsK556APc1wDea3SBSWqHXEimBxxbew
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    acc = xrpl.account.does_account_exist(address, client)
  File "/usr/local/lib/python3.8/dist-packages/xrpl/account/main.py", line 30, in does_account_exist
    return asyncio.run(main.does_account_exist(address, client, ledger_index))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/xrpl/asyncio/account/main.py", line 31, in does_account_exist
    await get_account_root(address, client, ledger_index=ledger_index)
  File "/usr/local/lib/python3.8/dist-packages/xrpl/asyncio/account/main.py", line 117, in get_account_root
    raise XRPLRequestFailureException(account_info.result)
xrpl.asyncio.clients.exceptions.XRPLRequestFailureException: Request failed, noNetwork: InsufficientNetworkMode

```

**Comment by mvadari** [comment]
It sounds like your node isn't synced to the network yet. What happens when you run `server_info`?
https://xrpl.org/diagnosing-problems.html

**Comment by JST5000** [comment]
@Hossein-Teimouri checking in - were you able to see what happens when you run `server_info`?

**Comment by JST5000** [comment]
Closing this for now as inactive - please re-open if you find steps to reproduce.
